import Foundation

enum LogLevel: String, CaseIterable {
    case info    = "INFO"
    case warning = "WARN"
    case error   = "ERROR"
    case smapi   = "SMAPI"   // TRACE/DEBUG from SMAPI file
}

enum LogSource {
    case app    // generated by StarHubTH itself
    case smapi  // loaded from SMAPI-latest.txt
}

struct LogEntry: Identifiable {
    let id = UUID()
    let timestamp: String
    let message: String
    let level: LogLevel
    let source: LogSource
    var modName: String? = nil
}
